name: springboot

spring:
  config:
    import: optional:/myconfig.properties

my:
  service:
    enabled: false
    remote-address: 192.168.1.1
    security:
      username: "admin"
      password: "admin"
      roles:
        - USER
