# 服务器默认端口 8080
server:
  port: 8070

spring:
  main:
    # 是否开启启动日志（默认为 true），true：开启；false：关闭
    log-startup-info: true
    # 是否延迟初始化，默认为 false
    lazy-initialization: true
    # banner 模式：console（打印到控制台）、log（打印到日志文件）、off（关闭）
    banner-mode: console

